model:
  loss: nllloss
  model_type: mnist
  optimizer: adam
storage:
  storage_config:
    storage_access_key: minioadmin
    storage_hostname: 192.168.1.12
    storage_port: 9000
    storage_secret_key: minioadmin
    storage_secure_mode: false
  storage_type: S3
