storage:
  storage_config:
    storage_access_key: minioadmin
    storage_hostname: 192.168.55.147
    storage_port: 9000
    storage_secret_key: minioadmin
    storage_secure_mode: false
  storage_type: S3


training:
  data:
    batch_size: 128
    dataset: cifar10
  loss: cross_entropy
  model:
    model_type: resnet20
  optimizer:
    optimizer: SFW
    weight_decay: 0.0001
    momentum: 0.9
    learning_rate: 0.1
    mode: initialization
    ord: 2
    rescale: gradient
    value: 30
  lr_scheduler:
    type: multistep
    lrmilestone: 100 150
    gamma: 0.1
    baseline_lr: 0.1

training_identifier:
  id: '21'
