model:
  learning_rate: 0.1
  loss: cross_entropy
  mode: initialization
  model_type: mnist
  momentum: 0.9
  optimizer: SFW
  ord: 2
  rescale: gradient
  value: 10
storage:
  storage_config:
    storage_access_key: minioadmin
    storage_hostname: 192.168.1.12
    storage_port: 9000
    storage_secret_key: minioadmin
    storage_secure_mode: false
  storage_type: S3
