model:
  learning_rate: 0.4
  loss: cross_entropy
  mode: initialization
  model_type: resnet20
  momentum: 0.9
  optimizer: adam
  ord: 2
  rescale: gradient
  value: 30
storage:
  storage_config:
    storage_access_key: minioadmin
    storage_hostname: 192.168.1.18
    storage_port: 9000
    storage_secret_key: minioadmin
    storage_secure_mode: false
  storage_type: S3
training:
  batch_size: 256
  dataset: cifar10
  trainer: model_training
training_identifier:
  id: '24'
