control:
  state: idle
  helper: keras

statestore:
  type: MongoDB
  mongo_config:
    username: fedn_admin
    password: password
    host: mongo
    port: 6534

flask:
  port: 8090

tensorboard:
  port: 6090
  path: data/runs

storage:
  storage_type: S3
  storage_config:
    storage_hostname: 10.0.0.34
    storage_port: 9000
    storage_access_key: fedn_admin
    storage_secret_key: password
    storage_secure_mode: False
