model:
  learning_rate: 0.1
  loss: cross_entropy
  mode: initialization
  model_type: resnet20
  momentum: 0.9
  optimizer: SFW
  ord: 2
  rescale: gradient
  value: 30
  weight_decay: 0.0001
  warm_up_epochs: 5
  epochs: 200
  baseline_lr: 0.1
  gamma: 0.1
  lrmilestone: 100 150
storage:
  storage_config:
    storage_access_key: minioadmin
    storage_hostname: 10.0.0.28
    storage_port: 9000
    storage_secret_key: minioadmin
    storage_secure_mode: false
  storage_type: S3
training:
  batch_size: 128
  dataset: cifar10
  trainer: model_training
training_identifier:
  id: "15"
