services:
  client5:
    command: sh -c 'python client.py settings/settings-client.yaml'
    container_name: client5
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            device_ids:
            - "0"
            driver: nvidia
    image: fedn-image:latest
    ports:
    - 8095:8095
    volumes:
    - ${PWD}:/app
    working_dir: /app/
version: '3.3'
