version: "3.3"

services:
  reducer:
    image: "pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime"
    container_name: "reducer"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              device_ids:
                - "MIG-GPU-6ff250df-07f5-cf8e-bfdb-d56c3c464126/2/0"
              driver: nvidia
    working_dir: /app/
    command: sh -c "pip install -r requirements.txt && python reducer.py"
    volumes:
      - ${PWD}:/app
    ports:
      - "8090:8090"
