version: '3.3'

services:
  reducer:
    image: "pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime"
    container_name: "reducer"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              device_ids:
                - '0'
              driver: nvidia
    working_dir: /app/
    command: sh -c "pip install -r requirements.txt && python reducer.py"
    volumes:
      - ${PWD}:/app
    ports:
      - "8090:8090"
