version: "3.3"

services:
  client2:
    image: "pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime"
    working_dir: /app/
    command: sh -c "pip install -r requirements.txt && python client.py"
    volumes:
      - "/home/kobe/Desktop/HardCoreNAS-FederatedLearning/FederatedLearningCode:/app"
    ports:
      - 8092:8092
    deploy:
      resources:
        reservations:
          devices:
          - driver: "nvidia"
            device_ids: ['0']
            capabilities: [ gpu ]

