version: '3.3'

services:
  minio:
    image: minio/minio:latest
    hostname: minio
    environment:
      - GET_HOSTS_FROM=dns
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_ROOT_USER=fedn_admin
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address minio:9001
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://minio:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data

  reducer:
    image: "python:3.8.9"
    working_dir: /app/
    command: sh -c "pip install -r requirements.txt && python reducer.py"
    volumes:
      - "D:/FederatedLearningCode:/app"
    ports:
      - 8090:8090

volumes:
  # CHANGE THIS IF YOU WANT TO PERSIST DATA ACROSS RUN's
  minio-data: