reducer:
  port: 8090
  hostname: 192.168.1.4

client:
  hostname: 192.168.1.4
  port: 8091

control:
  state: idle
  helper: keras

statestore:
  type: MongoDB
  mongo_config:
    username: fedn_admin
    password: password
    host: mongo
    port: 6534

storage:
  storage_type: S3
  storage_config:
    storage_hostname: 192.168.1.4
    storage_port: 9000
    storage_access_key: fedn_admin
    storage_secret_key: password
    storage_secure_mode: False